# Generated by Django 4.2.5 on 2023-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='long',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='links',
            name='short',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
