# Generated by Django 4.2.5 on 2023-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_links_long_alter_links_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
